# Generated by Django 2.2.7 on 2019-12-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(default='Developer', max_length=25)),
                ('projects', models.ManyToManyField(related_name='users', to='product.Project')),
            ],
        ),
    ]
