# Generated by Django 2.2.7 on 2019-11-09 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('estimated_time', models.PositiveIntegerField()),
                ('pic', models.CharField(max_length=50)),
                ('pbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='product.PBI')),
            ],
        ),
    ]
