# Generated by Django 2.2.7 on 2019-11-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('estimated_time', models.CharField(max_length=50)),
                ('pic', models.CharField(max_length=50)),
                ('sprint_no', models.IntegerField(default=0)),
                ('pbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.PBI')),
            ],
        ),
    ]
