# Generated by Django 2.2.7 on 2019-11-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_auto_20191107_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sprint',
        ),
        migrations.AlterField(
            model_name='task',
            name='pbi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='product.PBI'),
        ),
    ]
