# Generated by Django 2.2.7 on 2019-12-07 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_auto_20191207_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user.User'),
        ),
    ]
