# Generated by Django 2.2.7 on 2019-11-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0003_auto_20191107_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.IntegerField(max_length=50),
        ),
    ]
