# Generated by Django 2.2.7 on 2019-11-09 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('capacity', models.IntegerField(default=10)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['no'],
            },
        ),
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('sprint_no', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('story_point', models.PositiveIntegerField(default=0)),
                ('priority', models.IntegerField(default=1)),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pbis', to='product.Sprint')),
            ],
        ),
    ]
