# Generated by Django 2.2.7 on 2019-12-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('started', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=-1)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(default='Created', max_length=10)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='product.Project')),
            ],
            options={
                'ordering': ['no'],
            },
        ),
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('detail', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('story_point', models.PositiveIntegerField(default=0)),
                ('priority', models.IntegerField(default=1)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pbis', to='product.Project')),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pbis', to='product.Sprint')),
            ],
        ),
    ]
