# Generated by Django 2.2.7 on 2019-11-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('capacity', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ['no'],
            },
        ),
    ]
