# Generated by Django 3.0 on 2019-12-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='priority',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
