# Generated by Django 2.2.7 on 2019-11-08 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='sprint',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='product.Sprint'),
        ),
    ]
