# Generated by Django 2.2.7 on 2019-11-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_pbi_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pbis', to='product.Sprint'),
        ),
    ]
