# Generated by Django 2.2.7 on 2019-11-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sprint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(default='Created', max_length=10),
        ),
    ]
