# Generated by Django 2.2.7 on 2019-11-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20191124_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbi',
            name='sprint_no',
        ),
        migrations.AlterField(
            model_name='pbi',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
