# Generated by Django 2.2.7 on 2019-11-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20191125_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
