# Generated by Django 2.2.7 on 2019-12-03 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_project_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint', to='product.Project'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='no',
            field=models.IntegerField(default=-1),
        ),
    ]
