# Generated by Django 2.2.7 on 2019-12-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20191206_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
